spring:
  application:
    name: MrLamEL
  datasource:
    password: ${MYSQL_PASSWORD:root}
    username: ${MYSQL_USERNAME:root}
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/mrlamel?createDatabaseIfNotExist=true}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  servlet:
    context-path: /

jwt:
  signerKey: ${JWT_SIGNER_KEY:HOdXCyIIbIZEBThRVPkWEsVDhsqiLnsVAFfyBjJXabkrIPlFTlPzKCCDmMWopsSH}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173,http://localhost:300}


